import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}', './src/design/*.html'],
  theme: {
    extend: {
      colors: {
        primary: '#f3be4d',
        'inverse-primary': '#7a5900',
        'on-primary': '#402d00',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'on-background': '#e4e2e1',
        'inverse-surface': '#e4e2e1',
        'surface-tint': '#f3be4d',
        'surface-container-low': '#111111',
        'on-surface': '#e4e2e1',
        error: '#ffb4ab',
        'inverse-on-surface': '#303030',
        'on-primary-container': '#634700',
        'secondary-fixed': '#a3f69c',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#454747',
        'primary-container': '#e9b544',
        'surface-container-lowest': '#0b0b0b',
        'primary-fixed': '#ffdea3',
        'on-secondary-container': '#81d27c',
        'surface-bright': '#393939',
        'surface-variant': '#353535',
        'on-tertiary': '#2f3131',
        outline: '#4f4635',
        'tertiary-container': '#bcbcbc',
        background: '#0e0e0e',
        'tertiary-fixed': '#e2e2e2',
        'on-primary-fixed': '#261900',
        'on-primary-fixed-variant': '#5c4200',
        'tertiary-fixed-dim': '#c6c6c7',
        'secondary-fixed-dim': '#88d982',
        'surface-container-highest': '#2e2f2f',
        surface: '#131313',
        'error-container': '#93000a',
        'surface-container': '#1b1c1c',
        'primary-fixed-dim': '#f3be4d',
        'on-secondary': '#003909',
        'outline-variant': '#353535',
        'on-tertiary-fixed': '#1a1c1c',
        'secondary-container': '#005b14',
        'on-tertiary-container': '#4a4c4d',
        'on-error': '#690005',
        secondary: '#88d982',
        'surface-dim': '#0a0a0a',
        'on-surface-variant': '#9b8f7c',
        'surface-container-high': '#232424',
        tertiary: '#d8d9d9',
        'gold-muted': '#A6892C',
        'text-muted': '#888888',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
};
